In [64]:
import numpy as np

In [63]:
import numpy as np

# Define Probability and Actual Values Matrices
probability_matrix = np.array([
    [1.97, 3.90, 0.8, 0.1],
    [3.93, 23.5, 12.6, 2.99],
    [0.8, 12.7, 14.2, 6.68],
    [0, 3.09, 6.58, 6.16]
])

actual_values = np.array([
    [-50, 0, 10, 100],
    [-1, 0, 2, 4]
])

def calc_marginal_probability(prob_matrix: np.ndarray) -> np.ndarray:
    """Computes the marginal probability table by adding row and column sums."""
    row_sum = prob_matrix.sum(axis=1, keepdims=True)  # Shape (4,1)
    col_sum = prob_matrix.sum(axis=0, keepdims=True)  # Shape (1,4)
    total_sum = np.array([[prob_matrix.sum()]])       # Shape (1,1)

    # Append row sums as a new column, column sums as a new row, and total sum
    return np.vstack((np.hstack((prob_matrix, row_sum)), np.hstack((col_sum, total_sum))))

def is_return_independent(prob_matrix: np.ndarray) -> bool:
    """Checks if the first probability value equals the first marginal sum value."""
    marginal_prob = calc_marginal_probability(prob_matrix)
    return marginal_prob[0, 0] == marginal_prob[0, -1]  # Last column contains row sums

def calc_covariance(actual_values: np.ndarray, prob_matrix: np.ndarray) -> np.ndarray:
    """Calculates the covariance matrix using column sums."""
    return actual_values * prob_matrix.sum(axis=0, keepdims=True)

# Compute Expectation Matrix
expectation_matrix = calc_covariance(actual_values, probability_matrix) / 100
print(np.sum(expectation_matrix, axis=1))
print(expectation_matrix)


[15.998   1.2538]
[[-3.35    0.      3.418  15.93  ]
 [-0.067   0.      0.6836  0.6372]]


In [152]:
probablity_matrix = np.array([[1.97, 3.90, 0.8, 0.1],
                              [3.93, 23.5, 12.6, 2.99],
                              [0.8, 12.7,14.2,6.68],
                              [0,3.09,6.58,6.16]])

actual_x_small_firm = np.array([[-1, 0, 2,4]])
actual_y_big_firm = np.array([[-50, 0, 10,100]])

def calc_marginal_probability(prob_matrix: np.ndarray):
    row_sum = prob_matrix.sum(axis=1, keepdims=True)
    col_sum = prob_matrix.sum(axis=0, keepdims=True)
    total_sum = np.array([[prob_matrix.sum()]])
    return np.vstack((np.hstack((prob_matrix, row_sum)), np.hstack((col_sum, total_sum))))
    
def is_probablity_matrix_independent(prob_matrix: np.ndarray):
    marginal_probablity = calc_marginal_probability(probablity_matrix)
    row_prob = marginal_probablity[:-1,-1].reshape(-1,1)
    col_prob = marginal_probablity[-1:,:-1].reshape(1,-1)
    expected_joint = row_prob @ col_prob
    return np.allclose(prob_matrix, expected_joint, atol=1e-6)

def covariance_profits(actual_x_small_firm,actual_y_big_firm,prob_matrix):
    '''Formula for covariance = E[XY] - E[X]E[Y]'''
    prob_matrix = prob_matrix/100
    marginal_probablity = calc_marginal_probability(prob_matrix)
    EX = actual_y_big_firm * marginal_probablity[:-1,-1]
    EY = actual_x_small_firm * marginal_probablity[-1:,:-1]
    EXEY = actual_y_big_firm.reshape(-1,4) * actual_x_small_firm.reshape(4,-1)
    cov = (np.sum(EXEY.T * prob_matrix) - (np.sum(EX) * np.sum(EY)))
    corr = cov/()
    


##Function calls    
marginal_prob = calc_marginal_probability(probablity_matrix)
print(f"\n ***  Maginal Probablity Matrix *** \n",marginal_prob)
print(f"\n *** is probablity matrix independent *** \n", is_probablity_matrix_independent(probablity_matrix))
cov = covariance_profits(actual_x_small_firm, actual_y_big_firm,probablity_matrix)
print(cov)


 ***  Maginal Probablity Matrix *** 
 [[  1.97   3.9    0.8    0.1    6.77]
 [  3.93  23.5   12.6    2.99  43.02]
 [  0.8   12.7   14.2    6.68  34.38]
 [  0.     3.09   6.58   6.16  15.83]
 [  6.7   43.19  34.18  15.93 100.  ]]

 *** is probablity matrix independent *** 
 False
23.3028946
